# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lan Tian @ Blog
subtitle:
description:
keywords: Lan,Tian
author: Lan Tian
language:
- zh
- en
timezone: Asia/Shanghai

# URL
url: https://lantian.pub
root: /
permalink: :title.html
pretty_urls:
  trailing_index: false
  trailing_html: false


# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: archive
category_dir: category
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - usr/**/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true

markdown:
  render:
    html: true
    xhtmlOut: true
    breaks: true
    linkify: true
    typographer: false
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - '@lantian1998/markdown-it-graphviz'
    - name: '@lantian1998/markdown-it-highlightjs'
      options:
        auto: true
        code: false
        inline: true
    - markdown-it-ins
    - "@iktakahiro/markdown-it-katex"
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 1
    collisionSuffix: 'no'
    permalink: true
    permalinkClass: 'header-anchor'
    permalinkSide: 'right'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'

highlight:
  enable: false
prismjs:
  enable: false

feed:
  type:
    - atom
    - rss2
  path:
    - feed.xml
    - rss2.xml
  limit: 10
  autodiscovery: false

jsonFeed:
  limit: 10

baidu_url_submit:
  count: 10
  host: lantian.pub
  token: 8qQ6vZ9akZt4Koql
  path: baidu_urls.txt

algolia:
  appId: "MU6U5GYQMI"
  apiKey: "980c1cdb13ca7904d196dc74f757d7b1"
  adminApiKey: "faf2077ffbe58af3cf52534cdeaa5cbb"
  chunkSize: 5000
  indexName: "lantian"
  fields:
    - content:strip:truncate,0,2500
    - permalink
    - categories
    - tags
    - date
    - title

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  single_language_index: true

# Category & Tag
default_category: uncategorized
category_map:
  闲聊: chat
  自制软硬工具: creations
  转载: forward
  娱乐: fun
  计算机与客户端: modify-computer
  网站与服务端: modify-website
  一图流: one-pic
  随手记: random-notes
  Creations: creations
  Computers and Clients: modify-computer
  Website and Servers: modify-website
  Random Notes: random-notes
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: lantian

responsive_images:
  priority: 9
  rules:
    - pattern: '**/*.+(png|jpg|jpeg|webp)'
      sizes:
        thumb:
          width: 200
          height: 150

# Links
theme_config:
  disqus:
    short_name: lantian
    name: 'Lan Tian @ Blog'
    admin: lan_tian
    api_key: hxtAuBcAKlhxWnRnQlpLA6jIR54Wdh8aiVIIkm8Doha088NweAdV4jJXUahTWBb6
  announcement: >
    I'm starting to provide Chinese / English versions of some articles, switch with the Language menu above. 我开始提供部分文章的中文、英文翻译，请使用顶部语言菜单切换。

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:lantian1998/lantian1998.github.io.git
- type: baidu_url_submitter
